### ISSUE TITLE
Property xspec.template.name.entrypoint was circularly defined on oXygen 21.1

### ISSUE THREAD

**Issue by AirQuick** [xspec/oXygen-XML-editor-xspec-support#36] opened 2019-09-04 13:53 UTC
Can you take a look at this?
https://groups.google.com/d/msg/xspec-users/VGflYPxQ9xA/8aSP-pw_AAAJ

I reproduced it on the latest 21.1 using `[Oxygen samples]/xspec/xslt/escape-for-regex.xspec`.
Not repro on 21.0.2019022207.

**Comment by AlexJitianu** [comment] 2019-09-05 05:20
Hello,

I reproduced the issue myself. It is not related with the plugin, but with Oxygen version 21.1 which doesn't call anymore an API. The workaround is to: 

1. go to Options->Preferences..., on page Custom Editor Variables
2. press New on the bottom of the page, to create a new editor variable
3. The name of the variable should be: xspec.template.name.entrypoint
and the value some random characters. The value itself is not important,
the plugin will set the real value.
4. exit the dialog with O.K.

The next Oxygen maintenance release will have a fix for this issue so hopefully no one will encounter this issue anymore.

**Comment by AlexJitianu** [comment] 2019-09-09 04:56
I'll close this issue since there is nothing I can do on the plugin's side. If anyone else discovers it prior to us release a new Oxygen version, at least we have a documented workaround.

**Closed by AlexJitianu** 2019-09-09 04:56 UTC
